$name$FuncRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub "${AWS::StackName}-role"
    AssumedRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Prinicipal:
            Services:
              - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam:aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:

